export const TELECONSULTA_ESPECIALIZADA_PROCEDIMENTO = '0301010307'

export const TELECONSULTA_ESPECIALIZADA_NOME =
  'TELECONSULTA MEDICA NA ATENCAO ESPECIALIZADA'

export const BPA_RECORD_TYPE = '03'

export const BPA_HEADER_TYPE = '01'

export const BPA_HEADER_LITERAL = '#BPA#'

export const BPA_ORIGEM_REGISTRO = 'EXT'

export const BPA_CARATER_ATENDIMENTO = '01'

export const BPA_QUANTIDADE = '000001'

export const BPA_LINEBREAK = '\r\n'

export const BPA_HEADER_LENGTH = 130

export const BPA_RECORD_LENGTH = 350

export const BPA_RECORDS_PER_SHEET = 20

export const BPA_VERSAO_SISTEMA_DEFAULT = 'TELEFARMED001'
