export { VdApiError, vdRequest } from './client'
export {
  buildTenantHeaders,
  getVdTenantScope,
  mergeTenantIntoBody,
  mergeTenantIntoQuery,
  setVdApiTenantScope,
} from './tenantScope'

export { fetchTenant, fetchVdPublicTenant } from './tenant'
export { checkCepEligibility, lookupCpf, register } from './cadastro'
export { fetchMe, login, logout, refresh } from './auth'
export {
  activateRunWalkContatoConfiancaSos,
  createRunWalkLocalComentario,
  createRunWalkLocal,
  createRunWalkLocalCoverUploadUrl,
  createRunWalkContatoConfianca,
  deleteRunWalkAtividade,
  deleteRunWalkContatoConfianca,
  deleteRunWalkPreparacaoRascunho,
  getRunWalkContatosConfianca,
  getRunWalkDisposicao,
  getRunWalkIntegracoesLeiturasTempoReal,
  getRunWalkMetasSemanais,
  getRunWalkMetasSemanaisProgresso,
  getRunWalkAtividade,
  getRunWalkAtividadesResumo,
  getRunWalkPlanoHoje,
  getRunWalkPreparacaoRascunho,
  listAllRunWalkAtividades,
  listRunWalkLocais,
  listRunWalkLocalComentarios,
  listRunWalkAtividades,
  patchRunWalkAtividadeCheckin,
  postRunWalkDisposicaoCheckin,
  postRunWalkLocalVoto,
  postRunWalkPlanoHojeAcao,
  putRunWalkMetasSemanais,
  putRunWalkPreparacaoRascunho,
  putRunWalkPlanoHoje,
  registerRunWalkAtividade,
  updateRunWalkContatoConfianca,
} from './runWalk'
export {
  appendRunWalkLiveSessionPoints,
  createRunWalkLiveSession,
  endRunWalkLiveSession,
} from './runWalkLiveShare'
export {
  addFunctionalTrainingFavorito,
  getFunctionalTrainingEstatisticasSemanais,
  getFunctionalTrainingFavoritos,
  listFunctionalTrainingSessoes,
  registerFunctionalTrainingSessao,
  removeFunctionalTrainingFavorito,
} from './functionalTraining'
export { deleteSleepLog, listSleepLogs, registerSleepLog } from './sleepTime'
export {
  createActiveMindSession,
  deleteActiveMindSession,
  getActiveMindWeeklyStats,
  listActiveMindSessions,
  mapActiveMindSessaoDtoToSession,
  mapActiveMindSessionToCreateInput,
} from './activeMind'
export {
  getMetricsProfile,
  updateMetricsProfile,
  getLatestWeight,
  getMetricsResumo,
  listActivityHistory,
  listBodyMeasurements,
  listHealthIntegrations,
  listHeartRateHistory,
  listHydrationHistory,
  listBloodPressureHistory,
  listGlucoseHistory,
  listWeightHistory,
  registerBodyMeasurement,
  registerHeartRate,
  registerHydration,
  registerBloodPressure,
  registerGlucose,
  registerWalk,
  registerWeight,
  syncActivityDaysBatch,
  updateHealthIntegration,
} from './metricas'
export {
  completePasswordRecovery,
  forgotPassword,
  requestPasswordRecovery,
  verifyPasswordRecoveryCode,
} from './passwordRecovery'

export type {
  CreateRunWalkAtividadeInput,
  ListRunWalkAtividadesQuery,
  RegisterRunWalkAtividadeResult,
  ResumoRunWalkAtividadesQuery,
  RunWalkAtividadeDetailDto,
  RunWalkAtividadeDto,
  RunWalkAtividadeListResultDto,
  RunWalkAtividadeSummaryDto,
  PatchRunWalkAtividadeCheckinInput,
  PatchRunWalkAtividadeCheckinResult,
  RunWalkAtividadesResumoDto,
  RunWalkResumoChartDayDto,
  RunWalkResumoHeatmapCellDto,
  RunWalkResumoHighlightDto,
  RunWalkResumoPeriodSummaryDto,
  RunWalkResumoTrendPointDto,
  RunWalkTrailPointDto,
  RunWalkMetasSemanaisDto,
  RunWalkMetasSemanaisProgressoDto,
  RunWalkDisposicaoCheckinDto,
  RunWalkDisposicaoCheckinResultDto,
  RunWalkDisposicaoDto,
  DispositionFactorDto,
  DispositionLevelDto,
  DispositionStateDto,
  DispositionMoodDto,
  CreateRunWalkDisposicaoCheckinInput,
  RunWalkPlanoHojeDto,
  RunWalkPlanoAcaoResultDto,
  RunWalkPlanoMenuAction,
  PutRunWalkPlanoHojeInput,
  TodayActivityDto,
  TodayActivityPresetDto,
  TodayActivityStepDto,
  TrustedContactDto,
  TrustedContactsListDto,
  CreateTrustedContactInput,
  UpdateTrustedContactInput,
  RunningRouteLocalDto,
  RunningRouteLocaisListDto,
  ListRunWalkLocaisQuery,
  CreateRunWalkLocalInput,
  RunWalkLocalCoverUploadUrlDto,
  RunningRouteSpotCommentDto,
  RunningRouteLocalVotoResultDto,
  RunningRouteLocalComentariosListDto,
  RunWalkIntegracoesLeiturasTempoRealDto,
  RunWalkPreparacaoRascunhoDto,
  RunWalkPreparacaoRascunhoResultDto,
  WeeklyCalendarActivityDto,
  WeeklyCalendarDayDto,
  WeeklyGoalStatsDto,
  WeeklyGoalTargetsDto,
} from './runWalk'
export type {
  CreateFunctionalTrainingSessaoInput,
  FunctionalTrainingFavoritosDto,
  FunctionalTrainingSessaoDto,
  FunctionalTrainingSessaoListResultDto,
  ListFunctionalTrainingSessoesQuery,
  RegisterFunctionalTrainingSessaoResult,
  WeeklyTrainingStatsDto,
} from './functionalTraining'
export type {
  CreateSleepTimeRegistroInput,
  ListSleepTimeRegistrosQuery,
  RegisterSleepTimeRegistroResult,
  SleepTimeRegistroDto,
  SleepTimeRegistroListResultDto,
} from './sleepTime'
export type {
  ActiveMindSessionListResultDto,
  ActiveMindSessaoDto,
  CreateActiveMindSessionInput,
  ListActiveMindSessionsQuery,
  RegisterActiveMindSessionResult,
  WeeklyActiveMindStatsByGameDto,
  WeeklyActiveMindStatsDto,
} from './activeMind'
export type {
  AtividadeDayRecordDto,
  BloodPressureHistoryEntryDto,
  BodyMeasurementsHistoryDto,
  GlucoseHistoryEntryDto,
  HeartRateHistoryEntryDto,
  HydrationDayRecordDto,
  IntegracaoMetricasDto,
  LatestWeightResult,
  MetricDataPointDto,
  MetricsProfileDto,
  MetricsResumoDto,
  MetricsResumoLatestDto,
  RegisterBloodPressureResult,
  RegisterBodyMeasurementResult,
  RegisterGlucoseResult,
  RegisterHeartRateResult,
  RegisterHydrationResult,
  RegisterWalkResult,
  RegisterWeightResult,
  SyncActivityDaysBatchResult,
  UpdateHealthIntegrationInput,
  UpdateHealthIntegrationResult,
  UpdateMetricsProfileInput,
} from './metricas'
export type {
  VdCadastroLookupResult,
  VdCepElegibilidadeResult,
  VdLoginResult,
  VdPacienteUser,
  VdPasswordRecoveryRequestResult,
  VdPasswordRecoveryVerifyResult,
  VdRegisterInput,
  VdRegisterResult,
  VdTenantResult,
  VdTenantScope,
} from '../../../types/vdApi'
